version: '2'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=tlm_develop
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432

  app:
    image: vidgar/tlm_app
    ports:
      - "80:3000"
    depends_on:
      - postgres

volumes:
  postgres:
