default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PSQL_name'] %>
  password: <%= ENV['PSQL_psw'] %>

development:
  <<: *default
  database: TLM_development

test:
  <<: *default
  database: TLM_test
